### ISSUE TITLE
Could this be moved into mvt-fixtures?

### ISSUE THREAD

**Issue by mapsam** [mapbox/mvt-bench-fixtures#1]
mvt-fixtures breaks out fixtures based on `valid` and `invalid` right now. Would it be worth adding a `bench` directory as well?

cc @springmeyer @BergWerkGIS

**Comment by wilhelmberg** [comment]
@mapsam similar to this? 
https://github.com/mapbox/mvt-bench-fixtures
Or are thinking of moving those over?

**Comment by mapsam** [comment]
@BergWerkGIS just curious if we could move this entire repo into the `mvt-fixtures` repo for maintainability purposes. We could add a `bench/` directory here: https://github.com/mapbox/mvt-fixtures/tree/master/fixtures

**Comment by wilhelmberg** [comment]
@mapsam fine with me.
@springmeyer ???

**Comment by springmeyer** [comment]
I created a separate repo for this because I don't feel like mvt-fixtures should hold any real-world or large data. I think mvt-fixtures should stay very small so that there is little cost to including it in downstream projects. Currently mvt-fixtures are `156kb` and created from scratch while mvt-bench-fixtures are `6.5MB` and created by fetching via mapbox API.

**Comment by mapsam** [comment]
👍

**Comment by springmeyer** [comment]
@mapsam @BergWerkGIS - push back if I'm missing something or if you feel like my tiny size dreams are limiting. However, if you don't, let's keep on trying to be small. In the process of checking sizes I noticed that the `_reserve` folder is larger than the fixture folder and so I created https://github.com/mapbox/mvt-fixtures/issues/11 over at `mvt-fixtures`.
